### ISSUE TITLE
Pick and bootstrap a static site generator

### ISSUE THREAD

**Issue by ramesius** [lendi-au/engineering-blog#1]

**Comment by ramesius** [comment]
https://gohugo.io seems like a decent choice

**Comment by jordan-simonovski** [comment]
@ramesius I think @ActuallyACat and @rozenraymond were keen on using Gatsby for this one 🤔

**Comment by rozenraymond** [comment]
I favour Gatsby over Hugo because it uses React under the hood which lots of us in Lendi is familiar with. Also, Gatsby has lots of plugins that we can utilise and its community is great too. 😁

**Comment by ramesius** [comment]
Gatsby seems great too. Happy to decide on gatsby for the above mentioned reasons 👍

**Comment by jordan-simonovski** [comment]
General consensus seems to be that Gatsby is the choice going forward. Closing off this ticket as decision made? :)
